default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 1234
  host: localhost
  port: 5432

development:
  <<: *default
  database: my_new_rails_app_development

test:
  <<: *default
  database: my_new_rails_app_test

production:
  <<: *default
  database: my_new_rails_app_production
